version: '3.8'

services:
  web1:
    image: nginx:alpine
    ports:
      - 8081:80
    volumes:
      - ./web1:/usr/share/nginx/html
  
  web2:
    image: nginx:alpine
    ports:
      - 8082:80
    volumes:
      - ./web2:/usr/share/nginx/html
  
  proxy:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
